### PR TITLE
Add project: macht.sprache.

### PR DESCRIPTION
**Pull request by timurc**
Ich bin bei Twitter über diese Übersicht gestoßen und dachte, unser Projekt passt gut dazu! Ich würde mich freuen, wenn wir hier auftauchen.

Wir sind von der Senatsverwaltung für Kultur und Europa im Rahmen von "Digitale Kompetenzen für Berlins Kulturbereich" 2021 gefördert und gerade mitten in der Umsetzung und laden Interessierte ein, sich zu beteiligen. 

Ich hoffe, ich habe in diesem PR die Leitlinien erfolgreich umgesetzt, falls nicht, bitte bescheid geben.

### CODE REVIEW

**Comment by timurc** [comment]
@dnsos I made the PR against `staging` instead of `main` because there was a note in the PR form to do so. But – I had checked out `main` initially and now looks like my PR would have 17 commits instead of 2. I could branch off `staging` again and cherry-pick my commits in there or add another PR against `main` if that helps.

**Comment by dnsos** [comment]
Hey @timurc, thank you for the contribution, we're taking a look at it now!

> @dnsos I made the PR against `staging` instead of `main` because there was a note in the PR form to do so. But – I had checked out `main` initially and now looks like my PR would have 17 commits instead of 2. I could branch off `staging` again and cherry-pick my commits in there or add another PR against `main` if that helps.

That note is indeed outdated. Thanks for pointing it out, we'll change that.

I've pointed your PR against `main` now and resolved a conflict. Perhaps you could also take another look to see if your data is as it should be.

**Review by dnsos — APPROVED** [review]
Hey @timurc, I've taken a look at the additions/changes and it looks all fine.

Super interesting project - merging this now!

**Comment by timurc** [comment]
Thank you!

**Pull request merged**
